spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.101.217.19:3306/danggeun?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: develop
    password: dangguen1!

  session:
    store-type: redis

  data:
    redis:
      host: localhost

  mail:
    host: smtp.gmail.com
    username: tnsqja012@gmail.com
    password: zpbuqrdqrueiaiah
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true