spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/danggeun?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: develop
    password: danggeun1!

  session:
    store-type: redis

  data:
    redis:
      host: localhost

  mail:
    host: smtp.gmail.com
    username: tnsqja012@gmail.com
    password: zpbuqrdqrueiaiah
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true