### 1. 게시글 등록
POST {{article-api}}
Content-Type: application/json

{
  "articleId": null,
  "userId": "develop_test",
  "commentId": null,
  "regionId": "regionId",
  "groupId": null,
  "subject": "develop create aritcle subject",
  "context": "null context",
  "articleType": 0,
  "price": null,
  "active": true,
  "registeredDate": null,
  "registeredId": "develop_test",
  "modifiedDate": null,
  "modifiedId": "develop_test"
}

### 2. 게시글 수정
PUT {{article-api}}
Content-Type: application/json

{
  "articleId": "ARTICLE20230915000011",
  "userId": "develop_test",
  "regionId": "regionId",
  "subject": "develop aritcle subject",
  "context": "null context modfiy",
  "articleType": 0,
  "price": null,
  "active": true,
  "modifiedDate": null,
  "modifiedId": "develop_test"
}

### 3. 게시글 삭제 -- @PathVariable 방식
DELETE {{article-api}}
Content-Type: application/json

{
  "articleId": "ARTICLE20230915000011",
  "userId": "develop_test",
  "modifiedId": "develop_test"
}

### 4-1. 게시글 목록 조회 -- @RequestParam 방식
GET {{article-api}}?articleType=GROUP

### 4-2. 게시글 상세 조회 -- @PathVariable 방식
GET {{article-api}}/ARTICLE00001