### 1. 게시글 등록
POST {{article-api}}
Content-Type: application/json

{
  "articleId": null,
  "userId": 9999,
  "commentId": null,
  "regionId": 9999,
  "groupId": null,
  "subject": "develop create article subject",
  "context": "null context",
  "articleType": 0,
  "price": null,
  "active": true
}

### 2. 게시글 수정
PUT {{article-api}}
Content-Type: application/json

{
  "articleId": 1,
  "userId": 9999,
  "regionId": 9999,
  "subject": "develop article subject",
  "context": "null context modify",
  "articleType": 0,
  "price": null
}

### 3. 게시글 삭제 -- @PathVariable 방식
DELETE {{article-api}}/1
Content-Type: application/json

### 4. 게시글 상세 조회 -- @PathVariable 방식
GET {{article-api}}/1

### 5. 게시글 전체 조회
GET {{article-api}}?page=3
